-- Seed: public exercise library (~100 exercises across 15 categories)

INSERT INTO public.exercises (name, category, equipment, instructions, is_public, owner_trainer_id) VALUES
-- squat (8)
('Back Squat', 'squat', 'barbell', 'Bar on upper traps, brace hard, sit down between your hips. Drive the floor away and stand tall.', true, NULL),
('Front Squat', 'squat', 'barbell', 'Bar racked on shoulders, elbows high. Stay upright as you sit down, then punch up through the floor.', true, NULL),
('Goblet Squat', 'squat', 'dumbbell', 'Hold the weight at your chest, elbows tucked. Squat between your knees and keep your chest proud.', true, NULL),
('Box Squat', 'squat', 'barbell', 'Sit back to the box under control, pause without relaxing, then drive up hard through your whole foot.', true, NULL),
('Overhead Squat', 'squat', 'barbell', 'Wide grip, bar locked out overhead. Keep armpits facing forward as you squat and stay tight throughout.', true, NULL),
('Zercher Squat', 'squat', 'barbell', 'Cradle the bar in your elbows, brace your core, and squat deep while keeping your torso tall.', true, NULL),
('Hack Squat', 'squat', 'machine', 'Back flat on the pad, feet mid-platform. Lower under control to depth, then press through your whole foot.', true, NULL),
('Leg Press', 'squat', 'machine', 'Feet hip-width on the platform. Lower until knees near 90 degrees, then press without locking out hard.', true, NULL),
-- hinge (9)
('Conventional Deadlift', 'hinge', 'barbell', 'Bar over midfoot, hips back, lats tight. Push the floor away and stand up with the bar close to your body.', true, NULL),
('Romanian Deadlift', 'hinge', 'barbell', 'Soft knees, push your hips straight back. Lower the bar down your thighs until you feel your hamstrings, then stand.', true, NULL),
('Sumo Deadlift', 'hinge', 'barbell', 'Wide stance, toes out, shins vertical. Wedge your hips down and back, then spread the floor as you stand.', true, NULL),
('Trap Bar Deadlift', 'hinge', 'other', 'Stand centered in the bar, hips back, chest up. Drive through the floor and finish tall with glutes squeezed.', true, NULL),
('Kettlebell Swing', 'hinge', 'kettlebell', 'Hike the bell back between your legs, then snap your hips forward. Let the hips power the float, not the arms.', true, NULL),
('Barbell Hip Thrust', 'hinge', 'barbell', 'Upper back on a bench, bar over hips. Drive through your heels and squeeze your glutes to a full lockout.', true, NULL),
('Good Morning', 'hinge', 'barbell', 'Bar on your back, soft knees. Hinge your hips back until your torso is near parallel, then stand back up.', true, NULL),
('Single-Leg Romanian Deadlift', 'hinge', 'dumbbell', 'Balance on one leg, hinge your hips back and reach the weight down. Keep hips square and stand up smoothly.', true, NULL),
('Glute Bridge', 'hinge', 'bodyweight', 'Lie on your back, feet close to your hips. Drive through your heels and squeeze your glutes at the top.', true, NULL),
-- lunge (7)
('Walking Lunge', 'lunge', 'dumbbell', 'Step forward and lower your back knee toward the floor. Push through your front foot and step through to the next rep.', true, NULL),
('Reverse Lunge', 'lunge', 'barbell', 'Step back and lower under control, front shin vertical. Drive through the front heel to return to standing.', true, NULL),
('Bulgarian Split Squat', 'lunge', 'dumbbell', 'Back foot on a bench, front foot planted. Drop straight down, then drive up through the front leg.', true, NULL),
('Step-Up', 'lunge', 'dumbbell', 'Full foot on the box. Drive through the top leg to stand tall — avoid pushing off the bottom foot.', true, NULL),
('Lateral Lunge', 'lunge', 'bodyweight', 'Step wide to the side, sit into that hip, and keep the other leg straight. Push back to center with control.', true, NULL),
('Curtsy Lunge', 'lunge', 'bodyweight', 'Step one leg back and across behind you, then lower. Keep your hips facing forward and drive up through the front foot.', true, NULL),
('Split Squat', 'lunge', 'barbell', 'Set a staggered stance and stay there. Lower your back knee toward the floor, then press up through the front leg.', true, NULL),
-- push_horizontal (8)
('Bench Press', 'push_horizontal', 'barbell', 'Feet planted, shoulder blades pinned to the bench. Lower the bar to your chest and press back over your shoulders.', true, NULL),
('Incline Bench Press', 'push_horizontal', 'barbell', 'Set the bench around 30 degrees. Touch the bar to your upper chest and press up and slightly back.', true, NULL),
('Close-Grip Bench Press', 'push_horizontal', 'barbell', 'Hands just inside shoulder width, elbows tucked. Lower to your lower chest and press with your triceps.', true, NULL),
('Dumbbell Bench Press', 'push_horizontal', 'dumbbell', 'Press the dumbbells over your chest, lower until you feel a stretch, and keep your shoulder blades set on the bench.', true, NULL),
('Incline Dumbbell Press', 'push_horizontal', 'dumbbell', 'On an incline bench, press the dumbbells up and slightly together. Control the lowering to your upper chest.', true, NULL),
('Push-Up', 'push_horizontal', 'bodyweight', 'Hands under shoulders, body in one straight line. Lower your chest to the floor and press away without sagging hips.', true, NULL),
('Dip', 'push_horizontal', 'bodyweight', 'Support yourself on the bars, lean slightly forward. Lower until shoulders reach elbow height, then press to lockout.', true, NULL),
('Machine Chest Press', 'push_horizontal', 'machine', 'Set the handles at mid-chest height. Press smoothly to full extension and control the return.', true, NULL),
-- push_vertical (6)
('Overhead Press', 'push_vertical', 'barbell', 'Bar at your collarbone, glutes and core braced. Press straight up and finish with the bar over midfoot.', true, NULL),
('Push Press', 'push_vertical', 'barbell', 'Quick shallow dip with your legs, then drive the bar overhead. Lock it out with your head through at the top.', true, NULL),
('Seated Dumbbell Shoulder Press', 'push_vertical', 'dumbbell', 'Back supported, dumbbells at shoulder height. Press up until your arms lock out, then lower with control.', true, NULL),
('Arnold Press', 'push_vertical', 'dumbbell', 'Start palms facing you at shoulder height. Rotate as you press so palms face forward at lockout.', true, NULL),
('Landmine Press', 'push_vertical', 'barbell', 'Half-kneeling or standing, bar at your shoulder. Press up and forward along the bar''s arc, ribs down.', true, NULL),
('Pike Push-Up', 'push_vertical', 'bodyweight', 'Hips high in a pike, hands shoulder-width. Lower the top of your head toward the floor and press back up.', true, NULL),
-- pull_horizontal (8)
('Bent-Over Row', 'pull_horizontal', 'barbell', 'Hinge to about 45 degrees, back flat. Pull the bar to your lower ribs and control it back down.', true, NULL),
('Pendlay Row', 'pull_horizontal', 'barbell', 'Torso parallel, bar on the floor each rep. Pull explosively to your lower chest, then reset dead on the floor.', true, NULL),
('One-Arm Dumbbell Row', 'pull_horizontal', 'dumbbell', 'Hand and knee on a bench, back flat. Pull the dumbbell to your hip and lower it with control — no torso twist.', true, NULL),
('Seated Cable Row', 'pull_horizontal', 'cable', 'Sit tall with a slight lean back. Pull the handle to your stomach, squeeze your shoulder blades, then reach forward.', true, NULL),
('Chest-Supported Dumbbell Row', 'pull_horizontal', 'dumbbell', 'Chest on an incline bench, arms hanging. Row the dumbbells to your hips and pause with shoulder blades squeezed.', true, NULL),
('T-Bar Row', 'pull_horizontal', 'barbell', 'Straddle the bar, hinge with a flat back. Pull the handles to your chest and lower under control.', true, NULL),
('Inverted Row', 'pull_horizontal', 'bodyweight', 'Hang under a bar with your body in a straight line. Pull your chest to the bar and lower slowly.', true, NULL),
('Face Pull', 'pull_horizontal', 'cable', 'Rope at face height. Pull toward your eyes, spreading the rope with thumbs back, and squeeze your rear delts.', true, NULL),
-- pull_vertical (6)
('Pull-Up', 'pull_vertical', 'bodyweight', 'Overhand grip just outside shoulders. Pull your chest toward the bar, chin over, and lower all the way down.', true, NULL),
('Chin-Up', 'pull_vertical', 'bodyweight', 'Underhand grip, shoulder-width. Pull your chin over the bar leading with your chest, then lower under control.', true, NULL),
('Lat Pulldown', 'pull_vertical', 'cable', 'Grip just outside shoulders, slight lean back. Pull the bar to your collarbone and control it back up.', true, NULL),
('Close-Grip Lat Pulldown', 'pull_vertical', 'cable', 'Neutral close grip, chest tall. Drive your elbows down to your sides and resist the weight on the way up.', true, NULL),
('Straight-Arm Pulldown', 'pull_vertical', 'cable', 'Arms long with a slight elbow bend. Sweep the bar down to your thighs using your lats, not your triceps.', true, NULL),
('Assisted Pull-Up', 'pull_vertical', 'machine', 'Set assistance so you can finish every rep. Pull your chin over the bar and lower for a slow three count.', true, NULL),
-- carry (4)
('Farmer''s Carry', 'carry', 'dumbbell', 'Heavy weight in each hand, shoulders back, ribs down. Walk tall with short, quick steps.', true, NULL),
('Suitcase Carry', 'carry', 'kettlebell', 'One heavy weight at your side. Walk tall without leaning — don''t let the load pull you sideways.', true, NULL),
('Overhead Carry', 'carry', 'kettlebell', 'Lock the weight out overhead, biceps by your ear. Walk slowly, keeping your ribs stacked over your hips.', true, NULL),
('Front Rack Carry', 'carry', 'kettlebell', 'Bells racked at your chest, elbows tucked. Brace your core and walk tall without arching your back.', true, NULL),
-- core (8)
('Plank', 'core', 'bodyweight', 'Forearms down, body in one straight line. Squeeze your glutes and brace like you''re about to be poked in the stomach.', true, NULL),
('Side Plank', 'core', 'bodyweight', 'Stack your feet, elbow under shoulder. Lift your hips into a straight line and hold without sagging.', true, NULL),
('Dead Bug', 'core', 'bodyweight', 'Low back pressed to the floor. Extend opposite arm and leg slowly, exhale fully, and return with control.', true, NULL),
('Bird Dog', 'core', 'bodyweight', 'From all fours, reach opposite arm and leg long. Keep your hips level and pause before switching sides.', true, NULL),
('Pallof Press', 'core', 'cable', 'Stand side-on to the anchor, hands at your chest. Press straight out and resist the pull to rotate.', true, NULL),
('Hanging Leg Raise', 'core', 'bodyweight', 'Hang from the bar without swinging. Curl your legs up toward your chest and lower them slowly.', true, NULL),
('Ab Wheel Rollout', 'core', 'other', 'From your knees, roll out as far as you can without your lower back arching, then pull back with your abs.', true, NULL),
('Russian Twist', 'core', 'dumbbell', 'Sit back to a 45-degree lean, chest tall. Rotate side to side with control, moving from your trunk, not your arms.', true, NULL),
-- cardio (7)
('Assault Bike', 'cardio', 'machine', 'Drive with both arms and legs. Settle into a rhythm you can hold, then push the pace in intervals.', true, NULL),
('Rowing Machine', 'cardio', 'machine', 'Sequence legs, then body, then arms. Drive hard with your legs and keep your strokes long and smooth.', true, NULL),
('SkiErg', 'cardio', 'machine', 'Reach tall, then drive the handles down using your lats and a crisp hip hinge. Stay long and rhythmic.', true, NULL),
('Jump Rope', 'cardio', 'other', 'Stay tall on the balls of your feet, small hops, wrists doing the work. Find a relaxed, steady rhythm.', true, NULL),
('Stationary Bike', 'cardio', 'machine', 'Set the seat so your knee stays slightly bent at the bottom. Hold a smooth, even cadence.', true, NULL),
('Stair Climber', 'cardio', 'machine', 'Stand tall with a light grip on the rails. Step through your whole foot and let your legs do the work.', true, NULL),
('Treadmill Run', 'cardio', 'machine', 'Run tall with quick, light steps landing under your hips. Build speed gradually across the session.', true, NULL),
-- mobility (7)
('World''s Greatest Stretch', 'mobility', 'bodyweight', 'From a long lunge, drop your inside elbow toward the floor, then rotate and reach to the ceiling. Breathe into each position.', true, NULL),
('Couch Stretch', 'mobility', 'bodyweight', 'Back foot up against a wall or bench, front foot planted. Squeeze the back glute and stay tall — breathe through it.', true, NULL),
('90/90 Hip Switch', 'mobility', 'bodyweight', 'Sit with both legs at 90 degrees. Rotate your knees side to side, keeping your chest tall through the transition.', true, NULL),
('Cat-Cow', 'mobility', 'bodyweight', 'From all fours, round your spine up on the exhale, then arch and look up on the inhale. Move slowly segment by segment.', true, NULL),
('Thread the Needle', 'mobility', 'bodyweight', 'From all fours, slide one arm under your body and rotate. Follow your hand with your eyes and breathe into the stretch.', true, NULL),
('Shoulder CARs', 'mobility', 'bodyweight', 'Make the biggest slow circle you can with one arm, keeping your torso still. Own every inch of the range.', true, NULL),
('Half-Kneeling Hip Flexor Stretch', 'mobility', 'bodyweight', 'In a half-kneeling stance, tuck your pelvis and squeeze the rear glute. Shift forward slightly until you feel the front of the hip.', true, NULL),
-- plyometric (6)
('Box Jump', 'plyometric', 'bodyweight', 'Swing your arms, jump, and land softly on the box in a quarter squat. Step down between reps.', true, NULL),
('Broad Jump', 'plyometric', 'bodyweight', 'Swing back, then explode forward with a big hip drive. Stick the landing soft and balanced.', true, NULL),
('Depth Jump', 'plyometric', 'bodyweight', 'Step off a low box, land, and immediately jump as high as you can. Spend as little time on the ground as possible.', true, NULL),
('Medicine Ball Slam', 'plyometric', 'other', 'Reach the ball tall overhead, then slam it into the floor with your whole body. Catch the bounce and repeat.', true, NULL),
('Jump Squat', 'plyometric', 'bodyweight', 'Dip into a quarter squat and jump for height. Land softly and reset your stance before the next rep.', true, NULL),
('Lateral Bound', 'plyometric', 'bodyweight', 'Push off one leg and bound sideways. Stick the landing on the other leg, hold briefly, then bound back.', true, NULL),
-- olympic (6)
('Power Clean', 'olympic', 'barbell', 'Pull from the floor, then extend hard through your hips and catch the bar on your shoulders in a partial squat.', true, NULL),
('Hang Clean', 'olympic', 'barbell', 'Start at mid-thigh. Jump the bar up with an aggressive hip extension and catch it in the front rack.', true, NULL),
('Clean and Jerk', 'olympic', 'barbell', 'Clean the bar to your shoulders, stand, then dip and drive it overhead, splitting or squatting under to lockout.', true, NULL),
('Snatch', 'olympic', 'barbell', 'Wide grip, bar close all the way up. Extend hard, pull under, and catch the bar overhead in a squat.', true, NULL),
('Power Snatch', 'olympic', 'barbell', 'Same wide grip and big hip extension as the snatch, but catch the bar overhead above parallel.', true, NULL),
('Split Jerk', 'olympic', 'barbell', 'Dip straight down, drive the bar up, and split your feet fast. Lock out overhead before recovering your stance.', true, NULL),
-- isolation (8)
('Barbell Curl', 'isolation', 'barbell', 'Elbows pinned to your sides. Curl the bar up without swinging, then lower for a slow count.', true, NULL),
('Hammer Curl', 'isolation', 'dumbbell', 'Palms facing each other. Curl the dumbbells up with your elbows still, and control the lowering.', true, NULL),
('Cable Triceps Pushdown', 'isolation', 'cable', 'Elbows glued to your ribs. Press the handle down to full lockout and let it rise only to elbow height.', true, NULL),
('Lying Triceps Extension', 'isolation', 'barbell', 'Lower the bar toward your forehead with elbows pointed up, then extend back to lockout using only your triceps.', true, NULL),
('Dumbbell Lateral Raise', 'isolation', 'dumbbell', 'Slight bend in the elbows. Raise the dumbbells out to shoulder height, leading with your elbows, and lower slowly.', true, NULL),
('Leg Extension', 'isolation', 'machine', 'Pad on your shins, back against the seat. Extend to a full squeeze at the top, then lower with control.', true, NULL),
('Lying Leg Curl', 'isolation', 'machine', 'Hips pressed into the pad. Curl your heels to your glutes and resist the weight all the way back.', true, NULL),
('Standing Calf Raise', 'isolation', 'machine', 'Rise all the way onto your toes, pause at the top, then lower until you feel a deep stretch in your calves.', true, NULL),
-- other (2)
('Sled Push', 'other', 'other', 'Arms locked on the poles, body at a 45-degree lean. Drive with powerful, choppy steps and keep the sled moving.', true, NULL),
('Battle Ropes', 'other', 'other', 'Athletic stance, slight knee bend. Whip the ropes in a steady rhythm from your shoulders and keep breathing.', true, NULL);
